### ISSUE TITLE
Torch Not Downloading

### ISSUE THREAD

**Issue by HollowMind100** [Delcos/Hentai-Diffusion#7]
When running the user bat file, the following error occurs

Traceback (most recent call last):
  File "C:\Users\Aaryan\Downloads\stable-diffusion-webui-master\stable-diffusion-webui-master\launch.py", line 250, in <module>
    prepare_enviroment()
  File "C:\Users\Aaryan\Downloads\stable-diffusion-webui-master\stable-diffusion-webui-master\launch.py", line 171, in prepare_enviroment
    run(f'"{python}" -m {torch_command}', "Installing torch and torchvision", "Couldn't install torch")
  File "C:\Users\Aaryan\Downloads\stable-diffusion-webui-master\stable-diffusion-webui-master\launch.py", line 34, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install torch.
Command: "C:\Users\Aaryan\Downloads\stable-diffusion-webui-master\stable-diffusion-webui-master\venv\Scripts\python.exe" -m pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 --extra-index-url https://download.pytorch.org/whl/cu113
Error code: 1
stdout: Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu113

stderr: ERROR: Could not find a version that satisfies the requirement torch==1.12.1+cu113 (from versions: none)
ERROR: No matching distribution found for torch==1.12.1+cu113

**Comment by ice051128** [comment]
Same

**Comment by Amaterasu77777** [comment]
Same

**Comment by Arekgkg13** [comment]
The issue is that python 3.11 isn't supported by pytorch, only 3.7-3.9 are supported by pytorch.  I tried downloading and installing 3.9, but that didn't work out either.

**Comment by Delcos** [comment]
Download anaconda. Then type in anaconda in the start menu and right click, run as admin, and it should open the terminal (not PowerShell the normal one). Then type in pip install pytorch and it should figure out the versions on its own. It pip isn't installed go download that too.

**Comment by Kingbokser** [comment]
Even with downloading anaconda the first error accures when downloading torch "pip install pytorch" doesn't work and it say something like "It's called 'torch'". When I do "pip install torch" it works, but then it failes when clicking the file, which should oben the game

**Comment by Sneffel** [comment]
Same as Kingbokser. Even if manually downloaded torch and torchvision through anaconda, it doesn't recognize it and fails.

**Comment by wildhooman** [comment]
Still having issues, I've tried reinstalling things, and going to previous versions of python (Which was a bad idea apparently). Nothing seems to be working, it just keeps saying the same as the top post. Manual installs haven't worked either.

**Comment by 21plots** [comment]
venv "C:\Users\Samson\Downloads\stable-diffusion-webui-master\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: <none>
Traceback (most recent call last):
  File "C:\Users\Samson\Downloads\stable-diffusion-webui-master\launch.py", line 294, in <module>
    prepare_environment()
  File "C:\Users\Samson\Downloads\stable-diffusion-webui-master\launch.py", line 209, in prepare_environment
    run_python("import torch; assert torch.cuda.is_available(), 'Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check'")
  File "C:\Users\Samson\Downloads\stable-diffusion-webui-master\launch.py", line 73, in run_python
    return run(f'"{python}" -c "{code}"', desc, errdesc)
  File "C:\Users\Samson\Downloads\stable-diffusion-webui-master\launch.py", line 49, in run
    raise RuntimeError(message)
RuntimeError: Error running command.
Command: "C:\Users\Samson\Downloads\stable-diffusion-webui-master\venv\Scripts\python.exe" -c "import torch; assert torch.cuda.is_available(), 'Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check'"
Error code: 1
stdout: <empty>
stderr: Traceback (most recent call last):
  File "<string>", line 1, in <module>
AssertionError: Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check


Its is something to do with gpu, does any one know how to add to commandline?

**Comment by Delcos** [comment]
What's the gpu brand?

**Comment by Sneffel** [comment]
> What's the gpu brand?

AMD Ryzen

**Comment by Delcos** [comment]
Add 
--skip-torch-cuda-test

To the bat file you use to run the software. It should be added as shown here. 

COMMAND_ARGS= --skip-torch-cuda-test

**Comment by 21plots** [comment]
How do I edit the bat file? Do I just change it to a text file then change back to bat?

**Comment by Delcos** [comment]
Open notepad, and then drag the bat file onto that.

**Comment by Sneffel** [comment]
> COMMAND_ARGS= --skip-torch-cuda-test
mine looks like this 
`set COMMANDLINE_ARGS= --skip-torch-cuda-test 
`
there's       **set**
launched it and still
_RuntimeError: Couldn't install torch._

**Comment by Jay200001** [comment]
> When running the user bat file, the following error occurs
> 
> Traceback (most recent call last): File "C:\Users\Aaryan\Downloads\stable-diffusion-webui-master\stable-diffusion-webui-master\launch.py", line 250, in prepare_enviroment() File "C:\Users\Aaryan\Downloads\stable-diffusion-webui-master\stable-diffusion-webui-master\launch.py", line 171, in prepare_enviroment run(f'"{python}" -m {torch_command}', "Installing torch and torchvision", "Couldn't install torch") File "C:\Users\Aaryan\Downloads\stable-diffusion-webui-master\stable-diffusion-webui-master\launch.py", line 34, in run raise RuntimeError(message) RuntimeError: Couldn't install torch. Command: "C:\Users\Aaryan\Downloads\stable-diffusion-webui-master\stable-diffusion-webui-master\venv\Scripts\python.exe" -m pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 --extra-index-url https://download.pytorch.org/whl/cu113 Error code: 1 stdout: Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu113
> 
> stderr: ERROR: Could not find a version that satisfies the requirement torch==1.12.1+cu113 (from versions: none) ERROR: No matching distribution found for torch==1.12.1+cu113

Same

**Comment by Jay200001** [comment]
Same :<

**Comment by Sneffel** [comment]
Guys it's easy. Install the folder structure from the official repository and add the same args to the bat file. 
Sadly it didn't work with AMD.
